### ISSUE TITLE
error with "name 'conduct_mcmc' is not defined"

### ISSUE THREAD

**Issue by 4Urban** [psyphh/xifa#1]
Hi!

Thank you for providing the python package for _item factor analysis_.

I have a question or asking for a help about applying the package.

I followed your example instruction [IPIP 50 Items Example](https://github.com/psyphh/xifa/blob/master/examples/ipip50.ipynb).

In addition to it, I tried to run `grm.transform()` to **calculate the factor scores**, which I want to use for **shrinking the multiple items into some factors**.

However, it raised error with `name 'conduct_mcmc' is not defined` message.

So I reviewed the [original source file](https://github.com/psyphh/xifa/blob/295dcf752790b9bb6af065d8fe5a285391ef08a1/xifa/base.py#L297), but I also couldn't find the `conduct_mcmc()` function.

Is there any solution for this, especially in terms of getting the factor scores?

**Comment by psyphh** [comment]
It seems that I didn't export conduct_mcmc from source.
Thanks for pointing out this problem.
I will fix this problem recently.

PH

**Comment by 4Urban** [comment]
Thank you!

**Comment by psyphh** [comment]
The problem is fixed.
You can run the example on colab.
https://github.com/psyphh/xifa/blob/master/examples/ipip50.ipynb

PH

**Comment by 4Urban** [comment]
Thank you for the fast response :)

I checked your example on colab, too. Your code related to `transform()` works well, and the function also works well on Exploratory IFA.
